### ISSUE TITLE
Repo path not allowed

### ISSUE THREAD

**Issue by sbolten** [ValMati/borgserver-docker#7]
Hi, when trying to initialize a repo I always get "Repository path not allowed" also when not using restricted.

What is a valid path to provide when initialising a new repo?

**Comment by ValMati** [comment]
I have checked it and I have found a bug with the processing of the REXTRICT_TO_PATH variable. I have released a new version of 'borgserver' (ver. 0.1.1) which fixes that bug.

With this new version to initialise a new repository:
```
$ borg init --encryption=repokey ssh://borguser@serverIP/PATH
```

'PATH' can be an absolute path (/backups/repo1) or a relative path (repo1). Remember that 'PATH' is inside the container and must be a volume so that it is not lost when the container is removed.

**Comment by sbolten** [comment]
Thx a lot this solved the issue - althout I cannot use a relative path - but thats not really a problem.

One other thing I noticed: When logging (ssh) into the machine I always the message: client_input_hostkeys: received duplicated ssh-rsa host key........ I am pretty sure, that I have not distributed the borg server host key (generated when docker is inited) to any other server....

**Comment by ValMati** [comment]
Thanks to you for the feedback. I started this as something for personal use and it is very nice to see that there is someone who can find it useful.

Regarding the relative paths. The base path is '/home/borguser' (I'm thinking I should change it to /backups), so if you wanted to backup to '/backups/client1backup' the 'borg init' should look like this:

```
$ borg init --encryption=repokey ssh://borguser@borgserver/../../backups/client1backup
```


Think about mounting a volume on the path you want to backup to.

About the duplicate key message I don't know what it could be, could you share the docker-compose.yml or the command with which you are launching the borgserver container?

**Comment by sbolten** [comment]
First of all: Thx for sharing this image. Really appreciated !!!!

Regarding relative paths I'am now backing up to "ssh://borguser@borgserver:2022/backups/stephan/TEST"
This is working quite well. I thought with "relative" I could even omit the "backups/stephan" part - anyway I am happy with the above.

"duplicate key" - see below my compose yaml. Only thing of interest in there is the hostname - which does reflect the actual hostname without the port. Maybe there is something witht the port (2022 is the public port) - maybe that's a problem here - I cannot use port 22 since this is ocupied by the underlying host machine - just guessing.....

```
services:
    borgserver:
        container_name: borgserver
        image: valmati/borgserver
        hostname: borg.bolten.ch
        environment:
            - UID=1000
            - GID=1000
            - TZ=Europe/Zurich
            - RESTRICT_TO_PATH=true
        ports:
            - "2022:22"
        volumes:
            - /srv/dev-disk-by-label-icybox/borg/host_keys:/etc/ssh/host_keys/
            - /srv/dev-disk-by-label-icybox/borg/authorized_keys:/etc/authorized_keys/:ro
            - /srv/dev-disk-by-label-icybox/borg/backups:/backups

        restart: unless-stopped
```

Thx and all the best - Stephan
